name: SonarQube_ON

on:
  workflow_dispatch: # This enables manual trigger

jobs:
  sonarqube_on:
    runs-on: ubuntu-latest
    
    steps:

    - name: 🔎 Print Secret Values
        run: |
          echo "Printing secret values..."
          echo "VERSION_NUMBER: ${{ secrets.c }}"
