name: SonarQube_ON

on:
  workflow_dispatch: # This enables manual trigger

jobs:
  sonarqube_on:
    runs-on: ubuntu-latest
    
    steps:

    - name: Stop SonarQube if no scans are in progress
      run: |
        echo "Checking for active SonarQube scans..."
        RESPONSE=$(curl -s "http://13.201.109.77:9000/api/ce/activity?status=IN_PROGRESS")
        TASKS_COUNT=$(echo "$RESPONSE" | jq '.tasks | length')
        echo "Active scan count: $TASKS_COUNT"
    
        if [ "$TASKS_COUNT" -eq 0 ]; then
          echo "No scans in progress. Stopping SonarQube..."
          curl -X POST https://ftqp5itzh1.execute-api.ap-south-1.amazonaws.com/default/sonarqube_control \
            -H "Content-Type: application/json" \
            -d '{"control":"stop"}'
        else
          echo "There are still scans in progress. Skipping shutdown for now."
        fi
