name: SonarQube_ON

on:
  push:
    branches:
      - main

jobs:
  sonarqube_on:
    runs-on: ubuntu-latest

    steps:
      - name: Print and add 3 to VERSION_NUMBER
        run: |
          # Get the secret value (make sure it's treated as a number)
          VERSION_NUMBER=${{ secrets.C }}

          # Convert the secret to an integer and add 3
          UPDATED_VERSION=$((VERSION_NUMBER + 3))

          # Print the original and updated values
          echo "Original VERSION_NUMBER: $VERSION_NUMBER"
          echo "Updated VERSION_NUMBER after adding 3: $UPDATED_VERSION"
