name: SonarQube_ON

on:
  workflow_dispatch:

jobs:
  sonarqube_on:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🔓 Unmask and print secret (debug use only)
        run: |
          echo "::remove-matcher owner=secret" # disables masking temporarily
          echo "VERSION_NUMBER (unmasked): ${{ secrets.C }}"
